[package]
name = "calajson"
version = "0.1.0"
authors = ["Meredith Howard <mhoward@roomag.org>"]
edition = "2018"

[dependencies]
calamine = "~0.14.6"
clap = "~2.32.0"
failure = "~0.1.2"
serde = "~1.0.79"
serde_json = "~1.0.32"
